sudo: false # run in a docker container
dist: trusty
language: rust
rust:
#  - stable
#  - beta
  - nightly
addons:
  apt:
    packages:
    - cmake
    - libboost-all-dev
before_script:
  - cd test/fastrtps && ./build.sh && cd ping_pong && cmake . && make