sudo: false # run in a docker container
dist: trusty # required for cmake version for fast-rtps
language: rust
rust:
#  - stable
#  - beta
  - nightly-2016-11-06
addons:
  apt:
    packages:
    - cmake
    - libboost-all-dev
before_script:
  - cd test/fastrtps && ./build.sh && cd ping_pong && cmake . && make