[package]
name = "rtps"
version = "0.1.0"
authors = ["Xavier Lange <xrlange@gmail.com>"]

[lib]
doctest = false

[dependencies]
"byteorder" = "*"
"bitflags" = "*"
"net2" = "*"
"serde" = "*"
"serde_json" = "*"
"clippy" = "*"

[[test]]
name = "test"
path = "test/mod.rs"