[package]
name = "rtps"
version = "0.1.0"
authors = ["Xavier Lange <xrlange@gmail.com>"]

[dependencies]
"byteorder" = "*"
"bitflags" = "*"
"net2" = "*"
"serde" = "*"
"serde_json" = "*"
"clippy" = "*"


# [[bin]]
# name = "multicast"
# src = "src/bin/multicast.rs"